//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorAppBak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tutor()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int id { get; set; }
        public string names { get; set; }
        public string last_names { get; set; }
        public string dni { get; set; }
        public string address { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string academic_group_name { get; set; }
        public Nullable<System.DateTime> academic_group_foundation_date { get; set; }
        public string academic_group_address { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
